### ISSUE TITLE
Unify the bash script

### ISSUE THREAD

**Issue by tianhaoz95** [tianhaoz95-xilinx/x-dockerized#2]
**Is your feature request related to a problem? Please describe.**

as the Dockerfiles are growing rapidly, having bash files for each one of them is inefficient.

**Describe the solution you'd like**

Some way to resue bash files

**Describe alternatives you've considered**

search for a way to reuse bash or go with the python route

**Additional context**

**Comment by tianhaoz95-xilinx** [comment]
Should put bash script in documentation only
